name: Issue Report
description: Create a report to help us improve Adam Image
assignees:
  - eduardofilo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report.

        Before creating the issue, follow these steps:

        1. Check the [FAQ](https://github.com/eduardofilo/RG350_adam_image/wiki/En:-7.-FAQ) and [Problem solving](https://github.com/eduardofilo/RG350_adam_image/wiki/En:-6.-Problem-solving) documents on the wiki to see if the problem you observed is already solved or has a known workaround.
        2. If it is more of a question than a problem, consider opening a [Discussion](https://github.com/eduardofilo/RG350_adam_image/discussions) post instead of opening an Issue.
        3. Think about whether the issue is with the image itself or with one of the pieces of software it contains (ODBeta, RetroArch, SimpleMenu, emulators).
        4. The software contained in the image is mostly homebrew and not perfect. Consider whether your request makes sense considering the situation.
        5. The image brings together the work of many people who have put in many hours of effort. If you encounter an issue that you have the capacity to solve on your own, consider taking some time to contribute with the solution to the collective work.

        In case of doubt about the version of the image being used, you can find out by viewing the contents of the file `/media/data/adam_version.txt`
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the issue is.
      placeholder: Tell us what you see
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: On which device did you observe the issue?
      options:
        - GCW-Zero
        - PocketGo2 v1
        - PocketGo2 v2
        - RG280V
        - RG280M v1.1 (without HDMI)
        - RG280M v1.0 (with HDMI)
        - RG350
        - RG350P
        - RG350M
        - RG300X
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: On which version did you observe the issue?
      options:
        - v1.0
        - v1.0.1
        - v1.0.2
        - v1.0.3
        - v1.1
        - v1.2
        - v1.3
        - v1.3.1
        - v1.4
        - v1.4.1
        - v1.4.2
        - v2.0
        - v2.1
    validations:
      required: true
